# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 3m
  tests: true
  skip-dirs-use-default: true

service:
  golangci-lint-version: 1.61.0
    
linters:
  disable-all: true
  enable:
    - whitespace # Tool for detection of leading and trailing whitespace
    # - wsl # Forces you to use empty lines
    - wastedassign # Finds wasted assignment statements
    - unconvert  # Unnecessary type conversions
    - tparallel # Detects inappropriate usage of t.Parallel() method in your Go test codes
    - thelper # Detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - stylecheck # Stylecheck is a replacement for golint
    - prealloc # Finds slice declarations that could potentially be pre-allocated
    - predeclared # Finds code that shadows one of Go's predeclared identifiers
    - nolintlint # Ill-formed or insufficient nolint directives
    # - nlreturn # Checks for a new line before return and branch statements to increase code clarity
    - misspell # Misspelled English words in comments
    - makezero # Finds slice declarations with non-zero initial length
    - lll # Long lines
    - importas  # Enforces consistent import aliases
    - gosec # Security problems
    - gofmt # Whether the code was gofmt-ed
    - goimports # Unused imports
    - goconst # Repeated strings that could be replaced by a constant
    - forcetypeassert # Finds forced type assertions
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, , , _, := f())
    - dupl # Code clone detection
    - errname # Checks that sentinel errors are prefixed with Err and error types are suffixed with Error
    - errorlint # Error wrapping introduced in Go 1.13
    - gocritic # gocritic is a Go source code linter that maintains checks that are not in other linters
    - errcheck # Errcheck is a go lint rule for checking for unchecked errors
    # - godox # Linter for TODOs and FIXMEs left in the code
    - gci # Gci checks the consistency of the code with the Go code style guide
    - mnd # mnd is a linter for magic numbers
    # - revive 
    - unparam # Unused function parameters

linters-settings:
  gofmt:
    simplify: true
  gocritic:
    enabled-checks:
      - ruleguard
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
     excludes:
      - G115  # Potential integer overflow when converting between integer types

issues:
  whole-files: true
  exclude-rules:
    - path: '(_test\.go|^test/.*)'
      linters:
        - gosec
        - unparam
        - lll
    - path: 'etherman/contracts/contracts_(banana|elderberry)\.go'
      linters:
        - dupl
  exclude-dirs:
    - tests
    - aggregator/db/migrations
  include:
    - EXC0012 # Exported (.+) should have comment( \(or a comment on this block\))? or be unexported
    - EXC0013 # Package comment should be of the form "(.+)...
    - EXC0014 # Comment on exported (.+) should be of the form "(.+)..."
    - EXC0015 # Should have a package comment
