with-expecter: true
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}Mock"
packages:
  github.com/0xPolygon/cdk/sequencesender:
    config:
      dir: ./sequencesender/mocks
      outpkg: mocks
    interfaces:
      EthTxMngr:
      Etherman:
      StreamClient:
  github.com/0xPolygon/cdk/sequencesender/txbuilder:
    config:
      dir: ./sequencesender/mocks
      outpkg: mocks
    interfaces:
      TxBuilder:
