with-expecter: true
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}Mock"
packages:
  github.com/0xPolygon/cdk/sequencesender:
    config:
      dir: ./sequencesender
    interfaces:
      EthTxMngr:
        config:
          filename: ethtxmngr_mock_test.go
      Etherman:
        config:
          filename: etherman_mock_test.go
  github.com/0xPolygon/cdk/sequencesender/txbuilder:
    config:
      dir: ./sequencesender
    interfaces:
      TxBuilder:
        config:
          filename: txbuilder_mock_test.go
          outpkg: sequencesender
