// Code generated by mockery. DO NOT EDIT.

package mocks_txbuilder

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// L1Client is an autogenerated mock type for the l1Client type
type L1Client struct {
	mock.Mock
}

type L1Client_Expecter struct {
	mock *mock.Mock
}

func (_m *L1Client) EXPECT() *L1Client_Expecter {
	return &L1Client_Expecter{mock: &_m.Mock}
}

// HeaderByNumber provides a mock function with given fields: ctx, number
func (_m *L1Client) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Header, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Header); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1Client_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type L1Client_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number *big.Int
func (_e *L1Client_Expecter) HeaderByNumber(ctx interface{}, number interface{}) *L1Client_HeaderByNumber_Call {
	return &L1Client_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", ctx, number)}
}

func (_c *L1Client_HeaderByNumber_Call) Run(run func(ctx context.Context, number *big.Int)) *L1Client_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*big.Int))
	})
	return _c
}

func (_c *L1Client_HeaderByNumber_Call) Return(_a0 *types.Header, _a1 error) *L1Client_HeaderByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1Client_HeaderByNumber_Call) RunAndReturn(run func(context.Context, *big.Int) (*types.Header, error)) *L1Client_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewL1Client creates a new instance of L1Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewL1Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *L1Client {
	mock := &L1Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
