// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/0xPolygon/cdk/aggsender/types"
	mock "github.com/stretchr/testify/mock"
)

// EpochNotifier is an autogenerated mock type for the EpochNotifier type
type EpochNotifier struct {
	mock.Mock
}

type EpochNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *EpochNotifier) EXPECT() *EpochNotifier_Expecter {
	return &EpochNotifier_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: ctx
func (_m *EpochNotifier) Start(ctx context.Context) {
	_m.Called(ctx)
}

// EpochNotifier_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type EpochNotifier_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EpochNotifier_Expecter) Start(ctx interface{}) *EpochNotifier_Start_Call {
	return &EpochNotifier_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *EpochNotifier_Start_Call) Run(run func(ctx context.Context)) *EpochNotifier_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EpochNotifier_Start_Call) Return() *EpochNotifier_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *EpochNotifier_Start_Call) RunAndReturn(run func(context.Context)) *EpochNotifier_Start_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *EpochNotifier) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// EpochNotifier_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type EpochNotifier_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *EpochNotifier_Expecter) String() *EpochNotifier_String_Call {
	return &EpochNotifier_String_Call{Call: _e.mock.On("String")}
}

func (_c *EpochNotifier_String_Call) Run(run func()) *EpochNotifier_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EpochNotifier_String_Call) Return(_a0 string) *EpochNotifier_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EpochNotifier_String_Call) RunAndReturn(run func() string) *EpochNotifier_String_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: id
func (_m *EpochNotifier) Subscribe(id string) <-chan types.EpochEvent {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan types.EpochEvent
	if rf, ok := ret.Get(0).(func(string) <-chan types.EpochEvent); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan types.EpochEvent)
		}
	}

	return r0
}

// EpochNotifier_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EpochNotifier_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - id string
func (_e *EpochNotifier_Expecter) Subscribe(id interface{}) *EpochNotifier_Subscribe_Call {
	return &EpochNotifier_Subscribe_Call{Call: _e.mock.On("Subscribe", id)}
}

func (_c *EpochNotifier_Subscribe_Call) Run(run func(id string)) *EpochNotifier_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EpochNotifier_Subscribe_Call) Return(_a0 <-chan types.EpochEvent) *EpochNotifier_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EpochNotifier_Subscribe_Call) RunAndReturn(run func(string) <-chan types.EpochEvent) *EpochNotifier_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewEpochNotifier creates a new instance of EpochNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEpochNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *EpochNotifier {
	mock := &EpochNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
