// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	prover "github.com/0xPolygon/cdk/aggregator/prover"
)

// ChannelMock is an autogenerated mock type for the AggregatorService_ChannelServer type
type ChannelMock struct {
	mock.Mock
}

type ChannelMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelMock) EXPECT() *ChannelMock_Expecter {
	return &ChannelMock_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *ChannelMock) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// ChannelMock_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type ChannelMock_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *ChannelMock_Expecter) Context() *ChannelMock_Context_Call {
	return &ChannelMock_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *ChannelMock_Context_Call) Run(run func()) *ChannelMock_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelMock_Context_Call) Return(_a0 context.Context) *ChannelMock_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelMock_Context_Call) RunAndReturn(run func() context.Context) *ChannelMock_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *ChannelMock) Recv() (*prover.ProverMessage, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *prover.ProverMessage
	var r1 error
	if rf, ok := ret.Get(0).(func() (*prover.ProverMessage, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *prover.ProverMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prover.ProverMessage)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelMock_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type ChannelMock_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *ChannelMock_Expecter) Recv() *ChannelMock_Recv_Call {
	return &ChannelMock_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *ChannelMock_Recv_Call) Run(run func()) *ChannelMock_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelMock_Recv_Call) Return(_a0 *prover.ProverMessage, _a1 error) *ChannelMock_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelMock_Recv_Call) RunAndReturn(run func() (*prover.ProverMessage, error)) *ChannelMock_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *ChannelMock) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelMock_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type ChannelMock_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *ChannelMock_Expecter) RecvMsg(m interface{}) *ChannelMock_RecvMsg_Call {
	return &ChannelMock_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *ChannelMock_RecvMsg_Call) Run(run func(m interface{})) *ChannelMock_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ChannelMock_RecvMsg_Call) Return(_a0 error) *ChannelMock_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelMock_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *ChannelMock_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *ChannelMock) Send(_a0 *prover.AggregatorMessage) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*prover.AggregatorMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ChannelMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *prover.AggregatorMessage
func (_e *ChannelMock_Expecter) Send(_a0 interface{}) *ChannelMock_Send_Call {
	return &ChannelMock_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *ChannelMock_Send_Call) Run(run func(_a0 *prover.AggregatorMessage)) *ChannelMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*prover.AggregatorMessage))
	})
	return _c
}

func (_c *ChannelMock_Send_Call) Return(_a0 error) *ChannelMock_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelMock_Send_Call) RunAndReturn(run func(*prover.AggregatorMessage) error) *ChannelMock_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *ChannelMock) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelMock_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type ChannelMock_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *ChannelMock_Expecter) SendHeader(_a0 interface{}) *ChannelMock_SendHeader_Call {
	return &ChannelMock_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *ChannelMock_SendHeader_Call) Run(run func(_a0 metadata.MD)) *ChannelMock_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *ChannelMock_SendHeader_Call) Return(_a0 error) *ChannelMock_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelMock_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *ChannelMock_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *ChannelMock) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelMock_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type ChannelMock_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *ChannelMock_Expecter) SendMsg(m interface{}) *ChannelMock_SendMsg_Call {
	return &ChannelMock_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *ChannelMock_SendMsg_Call) Run(run func(m interface{})) *ChannelMock_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ChannelMock_SendMsg_Call) Return(_a0 error) *ChannelMock_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelMock_SendMsg_Call) RunAndReturn(run func(interface{}) error) *ChannelMock_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *ChannelMock) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelMock_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type ChannelMock_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *ChannelMock_Expecter) SetHeader(_a0 interface{}) *ChannelMock_SetHeader_Call {
	return &ChannelMock_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *ChannelMock_SetHeader_Call) Run(run func(_a0 metadata.MD)) *ChannelMock_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *ChannelMock_SetHeader_Call) Return(_a0 error) *ChannelMock_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelMock_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *ChannelMock_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *ChannelMock) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// ChannelMock_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type ChannelMock_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *ChannelMock_Expecter) SetTrailer(_a0 interface{}) *ChannelMock_SetTrailer_Call {
	return &ChannelMock_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *ChannelMock_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *ChannelMock_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *ChannelMock_SetTrailer_Call) Return() *ChannelMock_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChannelMock_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *ChannelMock_SetTrailer_Call {
	_c.Run(run)
	return _c
}

// NewChannelMock creates a new instance of ChannelMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelMock {
	mock := &ChannelMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
