#!/bin/bash
# This is a postinstallation script so the service can be configured and started when requested
#
adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent cdk
if [ -d "/opt/cdk" ]
then
    echo "Directory /opt/cdk exists."
else
     mkdir -p /opt/cdk
     chown -R cdk /opt/cdk
fi
systemctl daemon-reload
