#!/bin/bash
### Common variables
KURTOSIS_ENCLAVE=cdk
TMP_CDK_FOLDER=tmp/cdk
DEST_KURTOSIS_PARAMS_YML=../$TMP_CDK_FOLDER/e2e-params.yml
KURTOSIS_FOLDER=${KURTOSIS_FOLDER:=../kurtosis-cdk}
USE_L1_GAS_TOKEN_CONTRACT=true
