name: Test e2e
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.21.x ]
        goarch: [ "amd64" ]
        e2e-group: [ "elderberry-validium", "elderberry-rollup" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}

    - name: Build Docker
      run: make build-docker
 
      # this is better to get the action in
    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=0.90.1
        kurtosis version

    - name: Disable kurtosis analytics
      shell: bash
      run: kurtosis analytics disable

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1


    - name: Test
      run: make test-e2e-${{ matrix.e2e-group }}
      working-directory: test
