name: Test Unittest
on: 
  push:
     branches:
      - '**'
  workflow_dispatch: {}
  
 
jobs:
  test-unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v3

    - name: Launch unittest
      run: make test