name: Test Unittest
on: 
  push:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  test-unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v3

    - name: Build Docker
      run: make test