# based on: https://github.com/0xPolygon/kurtosis-cdk/blob/jhilliard/multi-pp-testing/multi-pp-test.sh.md
name: Test e2e multi pp
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}


jobs:
  test-e2e-multi_pp:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.22.x ]
        goarch: [ "amd64" ]
        e2e-group:
          - "fork12-pessimistic"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}

    - name: Build Docker
      run: make build-docker
    
    - name: Checkout kurtosis-cdk
      uses: actions/checkout@v4
      with:
        repository: 0xPolygon/kurtosis-cdk
        path: kurtosis-cdk
        ref: jhilliard/multi-pp-testing
    
    - name: Install Kurtosis CDK tools
      uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk
    
    - name: Install polycli
      run: |
        git clone https://github.com/0xPolygon/polygon-cli -b jhilliard/alonso
        cd polygon-cli
        make install
        /usr/local/bin/polycli version

    - name: Setup Bats and bats libs
      uses: bats-core/bats-action@2.0.0

    - name: Test
      run: make test-e2e-multi-pessimistic

      working-directory: test
      env:
        KURTOSIS_FOLDER: ${{ github.workspace }}/kurtosis-cdk
        BATS_LIB_PATH: /usr/lib/
        agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
    
    - name: Dump enclave logs
      if: failure()
      run: kurtosis dump ./dump

    - name: Generate archive name
      if: failure()
      run: |
        archive_name="dump_run_with_args_${{matrix.e2e-group}}_${{ github.run_id }}"
        echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
        echo "Generated archive name: ${archive_name}"
        kurtosis service exec cdk cdk-node-001 'cat /etc/cdk/cdk-node-config.toml' > ./dump/cdk-node-config.toml

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ./dump
