name: Test e2e
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}


jobs:
  build-cdk-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: Build cdk docker image
      run: make build-docker
    
    - name: Save cdk image to archive
      run: docker save --output /tmp/cdk.tar cdk
    
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: cdk
        path: /tmp/cdk.tar

  test-fork9-cdk-validium-e2e:
    name: E2E test
    needs:
      - build-cdk-image
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@312383f0362623e3c0aa53c4ef5d6f2710a36092
    secrets: inherit
    with:
      docker-tag: local
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: cdk
      agglayer-e2e-ref: 312383f0362623e3c0aa53c4ef5d6f2710a36092
      kurtosis-cdk-enclave-name: cdk
      kurtosis-cdk-args: |
        {
          "zkevm_contracts_image": "leovct/zkevm-contracts:v6.0.0-rc.1-fork.9-patch.1",
          "zkevm_prover_image": "hermeznetwork/zkevm-prover:v6.0.6",
          "cdk_erigon_node_image": "hermeznetwork/cdk-erigon:v2.1.2",
          "zkevm_node_image": "hermeznetwork/zkevm-node:v0.7.3-RC1",
          "cdk_validium_node_image": "0xpolygon/cdk-validium-node:0.7.0-cdk",
          "cdk_node_image": "cdk",
          "gas_token_enabled": true,
          "gas_token_address": "",
          "additional_services": [
            "pless_zkevm_node"
          ],
          "data_availability_mode": "cdk-validium",
          "sequencer_type": "erigon",
          "agglayer_image": "ghcr.io/agglayer/agglayer:0.2.0-rc.19"
        }

  check-fork9-cdk-validium-e2e-result:
    name: Check E2E results
    needs:
      - test-fork9-cdk-validium-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork9-cdk-validium-e2e.result) }}

  test-fork11-rollup-e2e:
    name: E2E test
    needs:
      - build-cdk-image
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@312383f0362623e3c0aa53c4ef5d6f2710a36092
    secrets: inherit
    with:
      docker-tag: local
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: cdk
      agglayer-e2e-ref: 312383f0362623e3c0aa53c4ef5d6f2710a36092
      kurtosis-cdk-enclave-name: cdk
      kurtosis-cdk-args: |
        {
          "zkevm_contracts_image": "leovct/zkevm-contracts:v7.0.0-rc.2-fork.11-patch.1",
          "zkevm_prover_image": "hermeznetwork/zkevm-prover:v7.0.2-fork.11",
          "cdk_erigon_node_image": "hermeznetwork/cdk-erigon:v2.1.2",
          "zkevm_node_image": "hermeznetwork/zkevm-node:v0.7.0-fork11-RC1",
          "cdk_node_image": "cdk",
          "gas_token_enabled": true,
          "gas_token_address": "",
          "data_availability_mode": "rollup",
          "sequencer_type": "erigon",
          "agglayer_image": "ghcr.io/agglayer/agglayer:0.2.0-rc.19"
        }

  check-fork11-rollup-e2e-result:
    name: Check E2E results
    needs:
      - test-fork11-rollup-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork11-rollup-e2e.result) }}

  test-fork12-cdk-validium-e2e:
    name: E2E test
    needs:
      - build-cdk-image
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@312383f0362623e3c0aa53c4ef5d6f2710a36092
    secrets: inherit
    with:
      docker-tag: local
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: cdk
      agglayer-e2e-ref: 312383f0362623e3c0aa53c4ef5d6f2710a36092
      kurtosis-cdk-enclave-name: cdk
      kurtosis-cdk-args: |
        {
          "zkevm_contracts_image": "leovct/zkevm-contracts:v8.0.0-rc.4-fork.12-patch.1",
          "zkevm_prover_image": "hermeznetwork/zkevm-prover:v8.0.0-RC12-fork.12",
          "cdk_erigon_node_image": "hermeznetwork/cdk-erigon:v2.1.2",
          "cdk_node_image": "cdk",
          "gas_token_enabled": true,
          "gas_token_address": "",
          "data_availability_mode": "cdk-validium",
          "sequencer_type": "erigon",
          "agglayer_image": "ghcr.io/agglayer/agglayer@sha256:5715855f2cc6834bd84a99a33937915164648547d21bfb55198948b0ae4e0fad"
        }

  check-fork12-cdk-validium-e2e-result:
    name: Check E2E results
    needs:
      - test-fork12-cdk-validium-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork12-cdk-validium-e2e.result) }}

  test-fork12-rollup-e2e:
    name: E2E test
    needs:
      - build-cdk-image
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@312383f0362623e3c0aa53c4ef5d6f2710a36092
    secrets: inherit
    with:
      docker-tag: local
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: cdk
      agglayer-e2e-ref: 312383f0362623e3c0aa53c4ef5d6f2710a36092
      kurtosis-cdk-enclave-name: cdk
      kurtosis-cdk-args: |
        {
          "zkevm_contracts_image": "leovct/zkevm-contracts:v8.0.0-rc.4-fork.12-patch.1",
          "zkevm_prover_image": "hermeznetwork/zkevm-prover:v8.0.0-RC12-fork.12",
          "cdk_erigon_node_image": "hermeznetwork/cdk-erigon:v2.1.2",
          "cdk_node_image": "cdk",
          "gas_token_enabled": true,
          "gas_token_address": "",
          "data_availability_mode": "rollup",
          "sequencer_type": "erigon",
          "agglayer_image": "ghcr.io/agglayer/agglayer@sha256:5715855f2cc6834bd84a99a33937915164648547d21bfb55198948b0ae4e0fad"
        }

  check-fork12-rollup-e2e-result:
    name: Check E2E results
    needs:
      - test-fork12-rollup-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork12-rollup-e2e.result) }}
