name: Test e2e
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}


permissions:
  id-token: write
  contents: write

jobs:
  build-cdk-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x

    - name: Build cdk docker image
      run: make build-docker
    
    - name: Save cdk image to archive
      run: docker save --output /tmp/cdk.tar cdk
    
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: cdk
        path: /tmp/cdk.tar

  read-test-args:
    name: Read tests args
    runs-on: ubuntu-latest
    outputs:
      test-fork9-cdk-validium-e2e-args: ${{ steps.read-args.outputs.test-fork9-cdk-validium-e2e-args }}
      test-fork11-rollup-e2e-args: ${{ steps.read-args.outputs.test-fork11-rollup-e2e-args }}
      test-fork12-cdk-validium-e2e-args: ${{ steps.read-args.outputs.test-fork12-cdk-validium-e2e-args }}
      test-fork12-rollup-e2e-args: ${{ steps.read-args.outputs.test-fork12-rollup-e2e-args }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read kurtosis-cdk-args from file
        id: read-args
        run: |
          CONTENT=$(cat ./.github/test_fork9_cdk_validium_e2e_args.json | jq -c .)
          echo "test-fork9-cdk-validium-e2e-args=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_fork11_rollup_e2e_args.json | jq -c .)
          echo "test-fork11-rollup-e2e-args=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_fork12_cdk_validium_e2e_args.json | jq -c .)
          echo "test-fork12-cdk-validium-e2e-args=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_fork12_rollup_e2e_args.json | jq -c .)
          echo "test-fork12-rollup-e2e-args=${CONTENT}" >> $GITHUB_OUTPUT

  test-fork9-cdk-validium-e2e:
    name: E2E test
    needs:
      - build-cdk-image
      - read-test-args
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@d5b04cec05a949d93a5e893ce43be2e04c1b5249
    secrets: inherit
    with:
      kurtosis-cdk-ref: 99a912e78954ef495c8339e78c2f4c2a202f941d
      agglayer-e2e-ref: d5b04cec05a949d93a5e893ce43be2e04c1b5249
      test-name: test-fork9-cdk-validium-e2e
      kurtosis-cdk-args: ${{ needs.read-test-args.outputs.test-fork9-cdk-validium-e2e-args }}

  check-fork9-cdk-validium-e2e-result:
    name: Check E2E results
    needs:
      - test-fork9-cdk-validium-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork9-cdk-validium-e2e.result) }}

  test-fork11-rollup-e2e:
    name: E2E test
    needs:
      - build-cdk-image
      - read-test-args
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@d5b04cec05a949d93a5e893ce43be2e04c1b5249
    secrets: inherit
    with:
      kurtosis-cdk-ref: 99a912e78954ef495c8339e78c2f4c2a202f941d
      agglayer-e2e-ref: d5b04cec05a949d93a5e893ce43be2e04c1b5249
      test-name: test-fork11-rollup-e2e
      kurtosis-cdk-args: ${{ needs.read-test-args.outputs.test-fork11-rollup-e2e-args }}

  check-fork11-rollup-e2e-result:
    name: Check E2E results
    needs:
      - test-fork11-rollup-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork11-rollup-e2e.result) }}

  test-fork12-cdk-validium-e2e:
    name: E2E test
    needs:
      - build-cdk-image
      - read-test-args
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@d5b04cec05a949d93a5e893ce43be2e04c1b5249
    secrets: inherit
    with:
      kurtosis-cdk-ref: 99a912e78954ef495c8339e78c2f4c2a202f941d
      agglayer-e2e-ref: d5b04cec05a949d93a5e893ce43be2e04c1b5249
      test-name: test-fork12-cdk-validium-e2e
      kurtosis-cdk-args: ${{ needs.read-test-args.outputs.test-fork12-cdk-validium-e2e-args }}

  check-fork12-cdk-validium-e2e-result:
    name: Check E2E results
    needs:
      - test-fork12-cdk-validium-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork12-cdk-validium-e2e.result) }}

  test-fork12-rollup-e2e:
    name: E2E test
    needs:
      - build-cdk-image
      - read-test-args
    uses: agglayer/e2e/.github/workflows/cdk-e2e.yml@d5b04cec05a949d93a5e893ce43be2e04c1b5249
    secrets: inherit
    with:
      kurtosis-cdk-ref: 99a912e78954ef495c8339e78c2f4c2a202f941d
      agglayer-e2e-ref: d5b04cec05a949d93a5e893ce43be2e04c1b5249
      test-name: test-fork12-rollup-e2e
      kurtosis-cdk-args: ${{ needs.read-test-args.outputs.test-fork12-rollup-e2e-args }}

  check-fork12-rollup-e2e-result:
    name: Check E2E results
    needs:
      - test-fork12-rollup-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-fork12-rollup-e2e.result) }}
