name: Test e2e
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}


jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.22.x ]
        goarch: [ "amd64" ]
        e2e-group: [ "elderberry-validium", "elderberry-rollup" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}

    - name: Build Docker
      run: make build-docker
 
      # this is better to get the action in
    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=0.90.1
        kurtosis version

    - name: Disable kurtosis analytics
      shell: bash
      run: kurtosis analytics disable

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install polycli
      run: |
        POLYCLI_VERSION="${{ vars.POLYCLI_VERSION }}"
        tmp_dir=$(mktemp -d) 
        curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${POLYCLI_VERSION}/polycli_${POLYCLI_VERSION}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir" 
        mv "$tmp_dir"/* /usr/local/bin/polycli 
        rm -rf "$tmp_dir"
        sudo chmod +x /usr/local/bin/polycli
        /usr/local/bin/polycli version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: checkout kurtosis-cdk
      uses: actions/checkout@v4
      with:
        repository: 0xPolygon/kurtosis-cdk
        ref: fix/missing_cdk_config_rollupmanager
        path: "kurtosis-cdk"

    - name: Setup Bats and bats libs
      uses: bats-core/bats-action@2.0.0

    - name: Test
      run: make test-e2e-${{ matrix.e2e-group }}
      working-directory: test
      env:
        KURTOSIS_FOLDER: ${{ github.workspace }}/kurtosis-cdk
        BATS_LIB_PATH: /usr/lib/
